### ISSUE TITLE
请问如何加速全部端口。

### ISSUE THREAD

**Issue by Unlash** [mixool/rinetd#10]
0.0.0.0 1 0.0.0.0 99999
这样能否实现 加速全部端口

**Comment by mixool** [comment]
不能，要每行一个端口 不要包含22端口。
试试我最下面那个一键。

Unlash <notifications@github.com> 于 2018年6月3日周日 18:50写道：

**Comment by Unlash** [comment]
我使用deluge，他不是固定端口，所以无法在.conf 指定端口
没有直接加速全部端口的方法吗

**Comment by Unlash** [comment]
![20180603185743](https://user-images.githubusercontent.com/32661990/40885806-09fd2a4a-6760-11e8-9626-20473c25496c.png)
好像是可以得

**Comment by mixool** [comment]
换kvm-bbr或者使用lkl-bbr
主页下面那个一键支持添加端口段的。

Unlash <notifications@github.com> 于 2018年6月3日周日 18:57写道：

**Comment by Unlash** [comment]
用这个工具 一般vps都是ovz 
kvm-bbr 我也想用（）

**Comment by Unlash** [comment]
Release

rinetd(lkl) with bbr powered congestion control

wget "https://github.com/linhua55/lkl_study/releases/download/v1.2/rinetd_bbr_powered" -O /usr/bin/rinetd

rinetd(lkl) with bbr congestion control

wget "https://github.com/linhua55/lkl_study/releases/download/v1.2/rinetd_bbr" -O /usr/bin/rinetd

rinetd(lkl) with pcc congestion control

wget "https://github.com/linhua55/lkl_study/releases/download/v1.2/rinetd_pcc" -O /usr/bin/rinetd





lkl是这部分吗？

**Comment by mixool** [comment]
说错了，是uml版本的bbr

Unlash <notifications@github.com> 于 2018年6月3日周日 19:07写道：

**Comment by Unlash** [comment]
那是用lkl还是uml？

**Comment by mixool** [comment]
你自己选一个用好了，配置可以的话，用uml的bbr。google一下，就有说明

Unlash <notifications@github.com> 于 2018年6月3日周日 19:10写道：

**Comment by Unlash** [comment]
lkl也支持全部端口加速？

**Comment by Unlash** [comment]
看了下lkl 支持端口段
