### ISSUE TITLE
请问这样子就是生效了吗。

### ISSUE THREAD

**Issue by Unlash** [mixool/rinetd#13]
![tim 20180627154155](https://user-images.githubusercontent.com/32661990/41959850-b37588ba-7a20-11e8-838a-1a2f915f8366.png)

**Comment by mixool** [comment]
是的，然后top看占用，速度越快，占用越高。

**Comment by Unlash** [comment]
![tim 20180627212336](https://user-images.githubusercontent.com/32661990/41976737-5e619e7e-7a50-11e8-9ae0-40db2d658d16.png)
看到了 。老哥稳。
老哥加个telegram。
