### ISSUE TITLE
rinetd版本LKL应该对glibc的版本没要求

### ISSUE THREAD

**Issue by linhua55** [mixool/rinetd#3]
rinetd版本LKL应该对glibc的版本没要求，应该适用所有64位系统

**Comment by mixool** [comment]
是你编译的时候使用了更高的glibc2.4，我自己又不会编译

**Comment by linhua55** [comment]
其实想问的是，是否亲自验证了？这和编译没关系吧。  hijack版的需要glibc2.4以上，是因为某个需要用到的syscall最低支持glibc2.14。 而rinetd版没有这个限制。

**Comment by mixool** [comment]
恩，验证了的，那几个版本运行这个rinetd显示错误，我google了说是编译使用了更高版本的glibc,晚点发错误详情。记不得错误了。

**Comment by mixool** [comment]
/root/rinetd: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /root/rinetd)

**Comment by mixool** [comment]
yum install glibc 升级不到2。14 最新2.12～

**Comment by linhua55** [comment]
静态编译了一下，麻烦有时间测试一下：
只编译了 修改版BBR

wget "https://drive.google.com/uc?id=0B0D0hDHteoksaGgxNFBUX2FDaVk"

**Comment by mixool** [comment]
成功运行 ,有劳了

**Comment by linhua55** [comment]
好，谢谢
