### ISSUE TITLE
问一个端口设置问题 a question about the port

### ISSUE THREAD

**Issue by Noahsarker** [mixool/rinetd#4]
服务端口与加速端口能写一样不
例如ss端口 23333
配置文件可否写成
0.0.0.0 23333 ip 23333
应该会冲突吧？不过web应用肯定用80 443的，如果冲突那就把nginx那里改成别的 加速后一样可以这两个端口访问？

**Comment by mixool** [comment]
我是把所有需要加速的端口都是用0.0.0.0 23333 0.0.0.0 23333的方式一行一行的添加，不会冲突。

**Comment by mixool** [comment]
范例就是写的一样的啊，不冲突。

**Comment by Noahsarker** [comment]
好的 感谢
