### ISSUE TITLE
Failed

### ISSUE THREAD

**Issue by leenchan** [mixool/rinetd#5]
root@ubuntu-899244871-0g64q:~/rinetd# ./rinetd_bbr_powered -f -c rinetd.conf raw eth0
[    0.000000] Linux version 4.10.0+ (vagrant@archlinux.vagrant.vm) (gcc version 7.1.1 20170516 (GCC) ) #56 Sun Jun 25 18:59:40 CST 2017
[    0.000000] bootmem address range: 0x2b1730001000 - 0x2b1734000000
[    0.000000] Built 1 zonelists in Zone order, mobility grouping on.  Total pages: 16159
[    0.000000] Kernel command line:  virtio_mmio.device=268@0x1000000:1
[    0.000000] PID hash table entries: 256 (order: -1, 2048 bytes)
[    0.000000] Dentry cache hash table entries: 8192 (order: 4, 65536 bytes)
[    0.000000] Inode-cache hash table entries: 4096 (order: 3, 32768 bytes)
[    0.000000] Memory available: 64492k/0k RAM
[    0.000000] SLUB: HWalign=32, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
[    0.000000] NR_IRQS:4096
[    0.000000] lkl: irqs initialized
[    0.000000] clocksource: lkl: mask: 0xffffffffffffffff max_cycles: 0x1cd42e4dffb, max_idle_ns: 881590591483 ns
[    0.000002] lkl: time and timers initialized (irq2)
[    0.000006] pid_max: default: 4096 minimum: 301
[    0.000028] Mount-cache hash table entries: 512 (order: 0, 4096 bytes)
[    0.000031] Mountpoint-cache hash table entries: 512 (order: 0, 4096 bytes)
[    0.008844] console [lkl_console0] enabled
[    0.008860] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
[    0.009016] NET: Registered protocol family 16
[    0.009374] clocksource: Switched to clocksource lkl
[    0.009506] NET: Registered protocol family 2
[    0.009772] TCP established hash table entries: 512 (order: 0, 4096 bytes)
[    0.009793] TCP bind hash table entries: 512 (order: 0, 4096 bytes)
[    0.009818] TCP: Hash tables configured (established 512 bind 512)
[    0.009921] UDP hash table entries: 128 (order: 0, 4096 bytes)
[    0.009937] UDP-Lite hash table entries: 128 (order: 0, 4096 bytes)
[    0.010085] virtio-mmio: Registering device virtio-mmio.0 at 0x1000000-0x100010b, IRQ 1.
[    0.010442] workingset: timestamp_bits=62 max_order=14 bucket_order=0
[    0.010471] virtio-mmio virtio-mmio.0: Failed to enable 64-bit or 32-bit DMA.  Trying to continue, but this might not work.
[    0.010748] NET: Registered protocol family 10
[    0.011295] Segment Routing with IPv6
[    0.011324] sit: IPv6, IPv4 and MPLS over IPv4 tunneling driver
[    0.011615] Warning: unable to open an initial console.
[    0.011642] This architecture does not have kernel memory protection.
[    2.499435] random: fast init done

i=0
cnt=1
iov[0].iov_len=1500
write to fd netdev fails: Message too long

#conf file:
0.0.0.0 80 0.0.0.0 80

Ubuntu 17.10 Docker
Linux version 4.4.0-87-generic (buildd@lcy01-31) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) ) #110-Ubuntu SMP Tue Jul 18 12:55:35 UTC 2017

**Comment by mixool** [comment]
推荐使用最新的 [One-key script](https://github.com/linhua55/lkl_study#one-key-script)
